name: www.omrquiz.cloud
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@v4
      with:
          repository: smallize/omrquiz
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0 
          submodules: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.135.0'
          extended: true
    - name: Build 
      run: hugo --config "configs/www.omrquiz.cloud.toml","configs/common.omrquiz.cloud.toml" -b "https://www.omrquiz.cloud" --cleanDestinationDir --minify --templateMetrics --templateMetricsHints --enableGitInfo
    - name: Deploy
      run: hugo deploy --config "configs/www.omrquiz.cloud.toml" --maxDeletes=-1 --target "production" --invalidateCDN --force
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
